improve validations to return empty element name as valid value
teleporthq/teleport-code-generators pull request #570
Opened 2021-05-09 09:26 UTC by chavda-bhavik

I've modified `isValidElementName()` to return empty element name as valid value and updated regex now returns true for empty string.

2021-05-09 09:32 UTC, JayaKrishnaNamburu requested changes

2021-05-09 09:32 UTC, JayaKrishnaNamburu commented on packages/teleport-uidl-validator/src/decoders/custom-combinators.ts
> +      if (typeof json === 'string' && fileNameRegex.test(json)) {
Well, `empty-strings` are not valid element names. So, it will be great if we can do thr string length check and throw error if it is empty strings.

2021-05-09 09:32 UTC, JayaKrishnaNamburu commented on packages/teleport-uidl-validator/src/decoders/custom-combinators.ts
>        return Result.err({ message: `Invalid link attribute, received ${json}` })
Here, can you please update the message to `Invalid name`, instead of `link attribute`

2021-05-09 09:51 UTC, chavda-bhavik commented on packages/teleport-uidl-validator/src/decoders/custom-combinators.ts
> +      if (typeof json === 'string' && fileNameRegex.test(json)) {
@JayaKrishnaNamburu, means we need to throw an error for empty element name? was thinking that the empty element name is valid, and made change accordingly.

2021-05-09 09:58 UTC, JayaKrishnaNamburu commented on packages/teleport-uidl-validator/src/decoders/custom-combinators.ts
> +      if (typeof json === 'string' && fileNameRegex.test(json)) {
Yes, actually `name` field is optional. But if the field exists then it should be a valid name. So, `name` can't be a empty string.

2021-05-09 10:19 UTC, chavda-bhavik commented on packages/teleport-uidl-validator/src/decoders/custom-combinators.ts
> +      if (typeof json === 'string' && fileNameRegex.test(json)) {
I think that thing was already happening before, throwing an error if element `name` has an empty string, and it's optional.

2021-05-09 11:45 UTC, JayaKrishnaNamburu commented on packages/teleport-uidl-validator/src/decoders/custom-combinators.ts
> +      if (typeof json === 'string' && fileNameRegex.test(json)) {
Yes, the issue was to improve error message 😃

2021-05-10 10:36 UTC, chavda-bhavik commented
@JayaKrishnaNamburu validation throws error message as below, is this issue?
`      
 Error: UIDL Format Validation Error. Please check the following:
        - Path input.node.content.name: [object Object].
        is a DecoderError
`

2021-05-11 12:30 UTC, JayaKrishnaNamburu commented
@chavda-bhavik this is a error message that is already happening. The aim was to make it more easy to pin-point the type of error for the user 😄. Can you try by throwing the error directly with `throw new Error` instead of `Result.Error`. Because, anyways `Resut.Error` breaks the pipeline anyways. What you say ?

2021-05-11 14:15 UTC, chavda-bhavik commented
Yes, that would be great @JayaKrishnaNamburu. I will update that way.

2021-05-11 14:54 UTC, JayaKrishnaNamburu commented
Awesome, to explore this path will be a great help

2021-05-12 09:46 UTC, chavda-bhavik commented
By @JayaKrishnaNamburu throw new Error(''), we can see the message as below, can we go with this?
`

UIDL Format Validation Error. Please check the following: 
     - Path undefined: Error: Name attribute cannot be empty. 
     is a undefined 
`

2021-05-12 10:24 UTC, JayaKrishnaNamburu commented
> @JayaKrishnaNamburu by throw new Error(''), we can see the message as below, can we go with this? asking because `undefined` is coming for the path and for `DecoderError` or `ValidationError`.
> `
> 
> UIDL Format Validation Error. Please check the following:
> - Path undefined: Error: Name attribute cannot be empty.
> is a undefined
> `

Sounds good, can we repeat the same for isValidComponentName and isValidProjectName too please :)

2021-05-12 12:13 UTC, JayaKrishnaNamburu approved these changes, later dismissed

2021-05-12 12:19 UTC, JayaKrishnaNamburu commented
Thanks @chavda-bhavik for the PR 😄 💯

2021-05-12 12:19 UTC, JayaKrishnaNamburu approved these changes

2021-05-12 12:20 UTC, merged