feature/nested-url-support
teleporthq/teleport-code-generators pull request #725
Opened 2022-11-29 12:53 UTC by vylly

WIP: add support for nested url (folder/mypage) => this includes css files path management / component import management / folder generation

2022-12-05 05:25 UTC, JayaKrishnaNamburu requested changes
This is a little bit of bigger refactor than it looks. You need to make the changes here
https://github.com/teleporthq/teleport-code-generators/blob/development/packages/teleport-project-generator/src/utils.ts#L200

For now, we are actually not relying on `routerLink` to calculate the folder path. We depend on `path` inside `ProjectStrategy`. Since the requirement is depend on `routerLink` from now on. We need to take that into consideration while calculating the output options here.
https://github.com/teleporthq/teleport-code-generators/blob/development/packages/teleport-project-generator/src/utils.ts#L182

So, that path will be used back here automatically and written to the output
https://github.com/teleporthq/teleport-code-generators/blob/development/packages/teleport-project-generator/src/index.ts#L230

So, the path checks happens only once and be synced across all plugins and generators.

2022-12-05 08:39 UTC, JayaKrishnaNamburu commented
The main reason that we need to take `routeLink` into consideration now. Because, many frameworks needs the pages in that respective paths for the routes to work.

2022-12-11 13:49 UTC, JayaKrishnaNamburu requested changes

2022-12-11 13:49 UTC, JayaKrishnaNamburu commented on packages/teleport-plugin-css/src/index.ts
> +      cssFileName = cssFileName.split('/').pop()
Please move this check inside the `getStyleFileName` so we don't need to make this check every time we try to get the file name

2022-12-11 13:49 UTC, JayaKrishnaNamburu commented on packages/teleport-project-generator-html/src/index.ts
> +      prefix: '/public',
Can you check this, we don't need to add `/` the server takes care of it i think

2022-12-12 16:07 UTC, vylly commented on packages/teleport-project-generator-html/src/index.ts
> +      prefix: '/public',
I checked, for html specifically I needed to add this, if not the pages in subfolders will have relative asset paths to the public folder and it will not be valid
see: https://codesandbox.io/s/rctgk4 (with prefix: 'public')
and this: https://codesandbox.io/s/0rk9bp (with prefix: '/public')

I couldn't find another workaround so far

2022-12-12 16:18 UTC, vylly commented on packages/teleport-plugin-css/src/index.ts
> +      cssFileName = cssFileName.split('/').pop()
If you are talking about this `cssFileName = cssFileName.split('/').pop()` I cannot move it to the `getStyleFileName` as I only need his pop to happen when getting the filname to use it as a styleurl
If I insert this pop in the `getStyleFileName` function it breaks the css files generation as it uses this function as well but needs to be aware of the "/" contained in the filname in this case

2022-12-13 09:35 UTC, JayaKrishnaNamburu approved these changes
Cool, nice work @vylly

2022-12-13 10:30 UTC, merged