Handle CMS list repeater separately from CMS list node
teleporthq/teleport-code-generators pull request #818
Opened 2023-07-18 14:51 UTC by TudorCe

2023-07-19 10:04 UTC, JayaKrishnaNamburu commented
Can you share some more details @TudorCe regarding the change and expected behaviour etc

2023-07-20 10:21 UTC, JayaKrishnaNamburu commented
@TudorCe is the `cms-list-repeator` is what responsible for generating pagination buttons ?

2023-07-20 10:30 UTC, TudorCe commented
> 

Nono, the pagination buttons currently have nothing custom in code generators, they are generated and passed here as regular links from the GUI

2023-07-25 12:30 UTC, JayaKrishnaNamburu requested changes

2023-07-25 12:30 UTC, JayaKrishnaNamburu commented on packages/teleport-project-generator/src/resource.ts
> +    }
Regarding this one, looks like the `params` are not being sent all the time. We need to add a new value to UIDL. Which says the `params` additional to the actual content that can be taken. 
https://github.com/teleporthq/teleport-code-generators/blob/feat/better-fetch/packages/teleport-types/src/uidl.ts#L67C36-L67C50

As even now, in few cases the params are being sent and few places no. So,

```js
normalize(resolveContentfulResponse(response))
```

```js
normalize(response, params)
```

Let's discuss, we should change this 👍

2023-07-26 12:27 UTC, JayaKrishnaNamburu approved these changes

2023-07-26 12:28 UTC, merged